DROP SEQUENCE NOTICE_SEQ;
CREATE SEQUENCE NOTICE_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;

DROP TABLE NOTICE;
CREATE TABLE NOTICE
(
	N_NO NUMBER PRIMARY KEY, 			--공지 번호
	N_TITLE VARCHAR2(100) NOT NULL,		--공지 제목
	N_M_NO NUMBER,
	N_CONTENT VARCHAR2(2000),			--공지 내용
	N_DATE DATE,					   	--공지 작성일
	FOREIGN KEY (N_M_NO) REFERENCES MEMBERS (M_NO) -- 회원번호
);
