DROP SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;
DROP TABLE PRODUCT;
CREATE TABLE PRODUCT (                      -- 제품테이블
    P_NO NUMBER PRIMARY KEY,                 -- 제품번호
    P_NAME VARCHAR2(200) NOT NULL,  	  	 -- 제품명
    P_SIZE VARCHAR2(50) NOT NULL,            -- 제품 size(ex: S, M ,L)
    P_PRICE NUMBER NOT NULL,                 -- 제품 가격
    P_COLOR VARCHAR2(30),                    -- 제품 색상
    P_AMOUNT NUMBER NOT NULL,                -- 제품 수량
    P_REGDATE DATE,                          -- 제품 등록일
	P_CATEGORY VARCHAR2(50) NOT NULL,        -- 제품 카테고리
	P_IMAGE VARCHAR2(200)					 -- 제품 사진
);
-- P_SEASON 제품시즌

--OUTER-
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'HALF DOUBLE LONG COAT', 'S', 288000, 'CHARCOAL', 10, SYSDATE, 'OUTER', 'https://i.esdrop.com/d/kmKCToa3wK.jpg');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'HALF DOUBLE LONG COAT', 'M', 288000, 'CHARCOAL', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'HALF DOUBLE LONG COAT', 'L', 288000, 'CHARCOAL', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'HALF DOUBLE LONG COAT', 'S', 288000, 'NAVY', 10, SYSDATE, 'OUTER', 'https://i.esdrop.com/d/2QbieVxnlr.jpg');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'HALF DOUBLE LONG COAT', 'M', 288000, 'NAVY', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'HALF DOUBLE LONG COAT', 'L', 288000, 'NAVY', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'OUT POCKET PEA COAT ', 'S', 268000, 'HERRINGBONE', 10, SYSDATE, 'OUTER', 'https://i.esdrop.com/d/y8XkMRABo6.jpg');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'OUT POCKET PEA COAT ', 'M', 268000, 'HERRINGBONE', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'OUT POCKET PEA COAT ', 'L', 268000, 'HERRINGBONE', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'OUT POCKET PEA COAT ', 'S', 268000, 'NAVY', 10, SYSDATE, 'OUTER', 'https://i.esdrop.com/d/temp6gZFlW.jpg');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'OUT POCKET PEA COAT ', 'M', 268000, 'NAVY', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'WOOL MAXI - OVER MAC COAT', 'S', 288000, 'CHARCOAL CHECK', 10, SYSDATE, 'OUTER', 'https://i.esdrop.com/d/GzQDC6UMYm.jpg');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'WOOL MAXI - OVER MAC COAT', 'M', 288000, 'CHARCOAL CHECK', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'WOOL MAXI - OVER MAC COAT', 'L', 288000, 'CHARCOAL CHECK', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'SEMI-OVER MARSEILE DOUBLE JACKET', 'S', 258000, 'CHARCOAL CHECK', 10, SYSDATE, 'OUTER', 'https://i.esdrop.com/d/NgulGNO6QD.jpg');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'SEMI-OVER MARSEILE DOUBLE JACKET', 'M', 258000, 'CHARCOAL CHECK', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'SEMI-OVER MARSEILE DOUBLE JACKET', 'L', 258000, 'CHARCOAL CHECK', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'SEMI-OVER MARSEILE DOUBLE JACKET', 'S', 258000, 'AQUA MARINE', 10, SYSDATE, 'OUTER', 'https://i.esdrop.com/d/Wjexr3jrKL.jpg');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'SEMI-OVER MARSEILE DOUBLE JACKET', 'M', 258000, 'AQUA MARINE', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'SEMI-OVER MARSEILE DOUBLE JACKET', 'L', 258000, 'AQUA MARINE', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'Military Over Coat', 'S', 368000, 'Herringbone', 10, SYSDATE, 'OUTER', 'https://i.esdrop.com/d/KGjRBEwLYy.jpg');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'Military Over Coat', 'M', 368000, 'Herringbone', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'Military Over Coat', 'L', 368000, 'Herringbone', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'909 Single Jacket', 'S', 148000, 'Black', 10, SYSDATE, 'OUTER', 'https://i.esdrop.com/d/QpM5nyqeRS.jpg');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'909 Single Jacket', 'M', 148000, 'Black', 10, SYSDATE, 'OUTER','');
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'909 Single Jacket', 'L', 148000, 'Black', 10, SYSDATE, 'OUTER','');
--BAG--
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, 'Saddle Mini-Bag [Eppi leather]', 'FREE', 148000, 'NAVY', 0, SYSDATE, 'BAG', 'https://i.esdrop.com/d/1eVTfZH0t1.jpg');

--BLACKFRIDAY--
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, '20SS_ Modern Half-Double Blazer [wool blend]', 'S', 199000, 'NAVY', 0, SYSDATE, 'BLACKFRIDAY', 'https://i.esdrop.com/d/njIkmwBl5u.jpg');
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, '20SS_ Modern Half-Double Blazer [wool blend]', 'M', 199000, 'DARK NAVY', 0, SYSDATE, 'BLACKFRIDAY','');
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, '20SS_ Modern Half-Double Blazer [wool blend]', 'L', 199000, 'NAVY', 10, SYSDATE, 'BLACKFRIDAY','');
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, '20SS_New Collarless Blazer [wool blend]', 'S', 199000, 'BLACK', 0, SYSDATE, 'BLACKFRIDAY','https://i.esdrop.com/d/ZgcqLLfZDl.jpg');
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, '20SS_New Collarless Blazer [wool blend]', 'M', 199000, 'BLACK', 10, SYSDATE, 'BLACKFRIDAY','');
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, '20SS_New Collarless Blazer [wool blend]', 'L', 199000, 'BLACK', 10, SYSDATE, 'BLACKFRIDAY','');
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, '20SS_Technical Semi-Wide slacks[wool blend]', 'S', 119000, 'BLACK', 10, SYSDATE, 'BLACKFRIDAY','https://i.esdrop.com/d/cy3ySdkc7V.jpg');
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, '20SS_Technical Semi-Wide slacks[wool blend]', 'M', 119000, 'BLACK', 10, SYSDATE, 'BLACKFRIDAY','');
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, '20SS_Technical Semi-Wide slacks[wool blend]', 'L', 119000, 'BLACK', 10, SYSDATE, 'BLACKFRIDAY','');
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, 'NOAH Merino Wool One Tuck Pants', 'S', 129000, 'BLACK', 10, SYSDATE, 'BLACKFRIDAY','https://i.esdrop.com/d/wbkD3FU2GC.jpg');
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, 'NOAH Merino Wool One Tuck Pants', 'M', 129000, 'BLACK', 10, SYSDATE, 'BLACKFRIDAY','');
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, 'NOAH Merino Wool One Tuck Pants', 'L', 129000, 'BLACK', 10, SYSDATE, 'BLACKFRIDAY','');
